CREATE TABLE IF NOT EXISTS "Users"(Id integer primary key, Name text, LastLogin datetime, Pass text, IsVisible INTEGER DEFAULT (1) NOT NULL, IsAdmin INTEGER DEFAULT (0));
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE Logs (
	"TimeStamp" TEXT DEFAULT (datetime()),
	UserId INTEGER NOT NULL,
	"Action" TEXT,
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CONSTRAINT Logs_users_FK FOREIGN KEY (UserId) REFERENCES "Users"(Id)
);
CREATE TABLE Chores (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER NOT NULL,
	ChoreName TEXT NOT NULL,
	ChoreValue NUMERIC NOT NULL,
	Frequency TEXT NOT NULL,
	CONSTRAINT NewTable_Users_FK FOREIGN KEY (UserId) REFERENCES Users(Id)
);
CREATE TABLE ChoreLog (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER NOT NULL,
	ChoreId INTEGER NOT NULL,
	DateLogged TEXT NOT NULL,
	DateCompleted TEXT NOT NULL,
	CONSTRAINT ChoreLog_Users_FK FOREIGN KEY (UserId) REFERENCES Users(Id),
	CONSTRAINT ChoreLog_Chores_FK FOREIGN KEY (ChoreId) REFERENCES Chores(Id)
);
